name: Quantum
version: '${project.version}'
main: com.wynvers.quantum.Quantum
api-version: '1.21'
load: POSTWORLD
author: Robie
description: Advanced virtual storage with dynamic GUI builder and orders system

softdepend:
  - PlaceholderAPI
  - Nexo
  - Vault
  - LuckPerms
  - WorldEdit
  - WorldGuard

commands:
  quantum:
    description: Main Quantum command
    usage: /quantum <reload|help>
    aliases: [q]
  
  storage:
    description: Open virtual storage (view-only for players)
    usage: /storage
    aliases: [store, st]
  
  menu:
    description: Open custom menu
    usage: /menu <menu_name>
    aliases: [openmenu]
  
  qstorage:
    description: Manage storage (admin-only)
    usage: /qstorage <transfer|remove> <item|hand|all> [amount]
    aliases: [quantumstorage, qs]
    permission: quantum.admin
    permission-message: "\u00a7cYou don't have permission to manage storage. Only admins can use /qstorage commands."
  
  rechercher:
    description: Open orders categories menu
    usage: /rechercher
    aliases: [orders, ordres]
    permission: quantum.orders.search
  
  recherche:
    description: Search for active orders for an item
    usage: /recherche <item>
    aliases: [search, chercher]
    permission: quantum.orders.search
  
  offre:
    description: Create a buy order for an item
    usage: /offre <item> <quantity> <price>
    aliases: [order, createorder]
    permission: quantum.orders.create
  
  zoneexit:
    description: Force a player to exit a restricted zone (console only)
    usage: /zoneexit <player>
  
  tower:
    description: Tower progression system commands
    usage: /tower <progress|reset|tp|reload> [args]
    aliases: [towers, tour, tours]

permissions:
  quantum.*:
    description: All Quantum permissions
    default: op
    children:
      quantum.admin: true
      quantum.storage.use: true
      quantum.storage.transfer: true
      quantum.storage.remove: true
      quantum.menu.open: true
      quantum.menu.admin: true
      quantum.orders.*: true
      quantum.zone.bypass: true
      quantum.tower.*: true
  
  quantum.admin:
    description: Admin permissions (required for storage management and GUI interaction)
    default: op
  
  quantum.storage.use:
    description: View storage GUI (read-only)
    default: true
  
  quantum.storage.transfer:
    description: Transfer items to storage (admin-only)
    default: op
  
  quantum.storage.remove:
    description: Remove items from storage (admin-only)
    default: op
  
  quantum.menu.open:
    description: Use menu system
    default: true
  
  quantum.menu.admin:
    description: Open menus for other players
    default: op
  
  quantum.orders.*:
    description: All orders permissions
    default: true
    children:
      quantum.orders.search: true
      quantum.orders.create: true
  
  quantum.orders.search:
    description: Allows searching for orders and opening categories menu
    default: true
  
  quantum.orders.create:
    description: Allows creating buy orders
    default: true
  
  # Permissions pour les durées d'ordres (LuckPerms)
  # Définies dans config.yml sous orders.durations
  quantum.orders.vip:
    description: VIP order duration (7 days)
    default: false
  
  quantum.orders.vip+:
    description: VIP+ order duration (14 days)
    default: false
  
  quantum.orders.mvp:
    description: MVP order duration (30 days)
    default: false
  
  quantum.orders.mvp+:
    description: MVP+ order duration (60 days)
    default: false
  
  quantum.orders.elite:
    description: Elite order duration (90 days)
    default: false
  
  # Permissions pour les zones WorldGuard
  quantum.zone.bypass:
    description: Bypass zone restrictions (can enter and exit freely)
    default: op
  
  # Permissions pour le système de tours
  quantum.tower.*:
    description: All tower permissions
    default: op
    children:
      quantum.tower.progress: true
      quantum.tower.progress.others: true
      quantum.tower.reset: true
      quantum.tower.teleport: true
      quantum.tower.reload: true
  
  quantum.tower.progress:
    description: View own tower progress
    default: true
  
  quantum.tower.progress.others:
    description: View other players' tower progress
    default: op
  
  quantum.tower.reset:
    description: Reset tower progress (admin)
    default: op
  
  quantum.tower.teleport:
    description: Teleport to tower floors (admin/debug)
    default: op
  
  quantum.tower.reload:
    description: Reload tower configurations
    default: op
