name: Quantum
version: '${project.version}'
main: com.wynvers.quantum.Quantum
api-version: '1.21'
load: POSTWORLD
author: Robie
description: Advanced virtual storage with dynamic GUI builder

softdepend:
  - PlaceholderAPI
  - Nexo

commands:
  quantum:
    description: Main Quantum command
    usage: /quantum <reload|help>
    aliases: [q]
  
  storage:
    description: Open virtual storage
    usage: /storage
    aliases: [store, st]
  
  menu:
    description: Open custom menu
    usage: /menu <menu_name>
    aliases: [openmenu]
  
  qstorage:
    description: Manage storage (transfer/remove items)
    usage: /qstorage <transfer|remove> <item|hand|all> [amount]
    aliases: [quantumstorage, qs]

permissions:
  quantum.*:
    description: All Quantum permissions
    default: op
    children:
      quantum.admin: true
      quantum.storage: true
      quantum.storage.transfer: true
      quantum.storage.remove: true
      quantum.menu: true
  
  quantum.admin:
    description: Admin permissions
    default: op
  
  quantum.storage:
    description: Use storage system
    default: true
  
  quantum.storage.transfer:
    description: Transfer items to storage
    default: true
  
  quantum.storage.remove:
    description: Remove items from storage
    default: true
  
  quantum.menu:
    description: Use menu system
    default: true
