name: Quantum
version: '${project.version}'
main: com.wynvers.quantum.Quantum
api-version: '1.21'
load: POSTWORLD
author: Robie
description: Advanced virtual storage with dynamic GUI builder

softdepend:
  - PlaceholderAPI
  - Nexo

commands:
  quantum:
    description: Main Quantum command
    usage: /quantum <reload|help>
    aliases: [q]
  
  storage:
    description: Open virtual storage (view-only for players)
    usage: /storage
    aliases: [store, st]
  
  menu:
    description: Open custom menu
    usage: /menu <menu_name>
    aliases: [openmenu]
  
  qstorage:
    description: Manage storage (admin-only)
    usage: /qstorage <transfer|remove> <item|hand|all> [amount]
    aliases: [quantumstorage, qs]
    permission: quantum.admin
    permission-message: "§cYou don't have permission to manage storage. Only admins can use /qstorage commands."

permissions:
  quantum.*:
    description: All Quantum permissions
    default: op
    children:
      quantum.admin: true
      quantum.storage.use: true
      quantum.storage.transfer: true
      quantum.storage.remove: true
      quantum.menu.open: true
      quantum.menu.admin: true
  
  quantum.admin:
    description: Admin permissions (required for storage management and GUI interaction)
    default: op
  
  quantum.storage.use:
    description: View storage GUI (read-only)
    default: true
  
  quantum.storage.transfer:
    description: Transfer items to storage (admin-only)
    default: op
  
  quantum.storage.remove:
    description: Remove items from storage (admin-only)
    default: op
  
  quantum.menu.open:
    description: Use menu system
    default: true
  
  quantum.menu.admin:
    description: Open menus for other players
    default: op
