name: Quantum
version: '${project.version}'
main: com.wynvers.quantum.Quantum
api-version: '1.21'
load: POSTWORLD
author: Kazotaruu_
description: Advanced virtual storage with dynamic GUI builder and orders system

depend:
  - Nexo

softdepend:
  - PlaceholderAPI
  - Vault
  - LuckPerms
  - WorldEdit
  - WorldGuard

commands:
  quantum:
    description: Main Quantum command
    usage: /quantum <reload|help>
    aliases: [q]
  
  storage:
    description: Open virtual storage (view-only for players)
    usage: /storage
    aliases: [store, st]
  
  menu:
    description: Open custom menu
    usage: /menu <menu_name>
    aliases: [openmenu]
  
  qstorage:
    description: Manage storage (admin-only)
    usage: /qstorage <transfer|remove> <item|hand|all> [amount]
    aliases: [quantumstorage, qs]
    permission: quantum.admin
    permission-message: "§cYou don't have permission to manage storage. Only admins can use /qstorage commands."
  
  qscoreboard:
    description: Toggle scoreboard visibility
    usage: /qscoreboard [on|off|status] [player]
    aliases: [qsb]
  
  rechercher:
    description: Open orders categories menu
    usage: /rechercher
    aliases: [orders, ordres]
    permission: quantum.orders.search
  
  recherche:
    description: Search for active orders for an item
    usage: /recherche <item>
    aliases: [search, chercher]
    permission: quantum.orders.search
  
  offre:
    description: Create a buy order for an item
    usage: /offre <item> <quantity> <price>
    aliases: [order, createorder]
    permission: quantum.orders.create
  
  zoneexit:
    description: Force a player to exit a restricted zone (console only)
    usage: /zoneexit <player>
  
  tower:
    description: Tower progression system commands
    usage: /tower <progress|reset|tp|reload> [args]
    aliases: [towers, tour, tours]
  
  armor:
    description: Dungeon armor management commands
    usage: /armor <give|info|apply|upgrade> [args]
    aliases: [armure, armour, darmor]
  
  rune:
    description: Rune item management commands
    usage: /rune <give|list> [args]
    aliases: [runes]
  
  qexp:
    description: Manage player EXP
    usage: /qexp <player> <give|take|set|reset> [amount]
    permission: quantum.exp.admin
  
  healthbar:
    description: Change mob health display mode
    usage: /healthbar <pourcentage|coeurs|info>
    aliases: [hpbar, hp]

permissions:
  quantum.*:
    description: All Quantum permissions
    default: op
    children:
      quantum.admin: true
      quantum.storage.use: true
      quantum.storage.transfer: true
      quantum.storage.remove: true
      quantum.menu.open: true
      quantum.menu.admin: true
      quantum.orders.*: true
      quantum.zone.bypass: true
      quantum.tower.*: true
      quantum.armor.*: true
      quantum.rune.*: true
      quantum.exp.admin: true
      quantum.healthbar.use: true
  
  quantum.admin:
    description: Admin permissions (required for storage management and GUI interaction)
    default: op
  
  quantum.storage.use:
    description: View storage GUI (read-only)
    default: true
  
  quantum.storage.transfer:
    description: Transfer items to storage (admin-only)
    default: op
  
  quantum.storage.remove:
    description: Remove items from storage (admin-only)
    default: op
  
  quantum.menu.open:
    description: Use menu system
    default: true
  
  quantum.menu.admin:
    description: Open menus for other players
    default: op
  
  quantum.orders.*:
    description: All orders permissions
    default: true
    children:
      quantum.orders.search: true
      quantum.orders.create: true
  
  quantum.orders.search:
    description: Allows searching for orders and opening categories menu
    default: true
  
  quantum.orders.create:
    description: Allows creating buy orders
    default: true
  
  # Order duration permissions (LuckPerms)
  # Defined in config.yml under orders.durations
  quantum.orders.vip:
    description: VIP order duration (7 days)
    default: false
  
  quantum.orders.vip+:
    description: VIP+ order duration (14 days)
    default: false
  
  quantum.orders.mvp:
    description: MVP order duration (30 days)
    default: false
  
  quantum.orders.mvp+:
    description: MVP+ order duration (60 days)
    default: false
  
  quantum.orders.elite:
    description: Elite order duration (90 days)
    default: false
  
  # WorldGuard zone permissions
  quantum.zone.bypass:
    description: Bypass zone restrictions (can enter and exit freely)
    default: op
  
  # Tower system permissions
  quantum.tower.*:
    description: All tower permissions
    default: op
    children:
      quantum.tower.progress: true
      quantum.tower.progress.others: true
      quantum.tower.reset: true
      quantum.tower.teleport: true
      quantum.tower.reload: true
  
  quantum.tower.progress:
    description: View own tower progress
    default: true
  
  quantum.tower.progress.others:
    description: View other players' tower progress
    default: op
  
  quantum.tower.reset:
    description: Reset tower progress (admin)
    default: op
  
  quantum.tower.teleport:
    description: Teleport to tower floors (admin/debug)
    default: op
  
  quantum.tower.reload:
    description: Reload tower configurations
    default: op
  
  # Dungeon armor system permissions
  quantum.armor.*:
    description: All armor permissions
    default: op
    children:
      quantum.armor.give: true
      quantum.armor.apply: true
      quantum.armor.upgrade: true
  
  quantum.armor.give:
    description: Give dungeon armor pieces
    default: op
  
  quantum.armor.apply:
    description: Apply runes to armor
    default: op
  
  quantum.armor.upgrade:
    description: Upgrade runes on armor
    default: op
  
  # Rune item permissions
  quantum.rune.*:
    description: All rune permissions
    default: op
    children:
      quantum.rune.give: true
  
  quantum.rune.give:
    description: Give rune items to players
    default: op
  
  # EXP command permission
  quantum.exp.admin:
    description: Allows using /qexp to manage player EXP
    default: op
  
  # HealthBar system
  quantum.healthbar.use:
    description: Allows changing health bar display mode
    default: true
